using System.Text.Json.Serialization;

namespace Bezalel.Workers.StudioWorker.Models;

/// <summary>
/// Read model returned by the repository containing everything
/// the StudioWorker pipeline needs to render carousel slides.
/// Aligned with the new editorial JSON schema generated by CopywriterWorker.
/// </summary>
public record CarouselJobRecord(
    [property: JsonPropertyName("jobId")]          string             JobId,
    [property: JsonPropertyName("tema")]           string             Tema,
    [property: JsonPropertyName("paletaCores")]    PaletteRecord      Palette,
    [property: JsonPropertyName("slides")]         List<SlideRecord>  Slides
);

public record PaletteRecord(
    [property: JsonPropertyName("corFundoGeral")]       string CorFundoGeral,
    [property: JsonPropertyName("corTextoPrincipal")]   string CorTextoPrincipal,
    [property: JsonPropertyName("corDestaque")]         string CorDestaque
);

public record SlideRecord(
    [property: JsonPropertyName("order")]            int            Order,
    [property: JsonPropertyName("layoutType")]       string         LayoutType,
    [property: JsonPropertyName("headline")]         string         Headline,
    [property: JsonPropertyName("highlightWords")]   List<string>?  HighlightWords,
    [property: JsonPropertyName("body")]             string?        Body,
    [property: JsonPropertyName("imagePrompt")]      string         ImagePrompt
);
