using System.ComponentModel.DataAnnotations;

namespace Bezalel.Core.DTOs;

/// <summary>
/// Request DTO for POST /api/carousel.
/// The front-end sends the user's creative prompt/theme and
/// optional preferences. The rest is generated by the CopywriterWorker LLM.
/// </summary>
public class CreateCarouselRequest
{
    /// <summary>
    /// The user's theme or creative prompt, e.g. "5 dicas de marketing digital para iniciantes".
    /// </summary>
    [Required(ErrorMessage = "O tema/prompt é obrigatório.")]
    [MaxLength(500, ErrorMessage = "O tema não pode exceder 500 caracteres.")]
    public string Tema { get; set; } = string.Empty;

    /// <summary>
    /// Optional: desired number of slides (4–7). Defaults to 5 if not specified.
    /// The CopywriterWorker LLM will respect this count.
    /// </summary>
    [Range(4, 7, ErrorMessage = "O carrossel deve ter entre 4 e 7 slides.")]
    public int? SlideCount { get; set; }

    /// <summary>
    /// Optional: desired visual style for background generation,
    /// e.g. "clean and modern", "dark and bold", "pastel and soft".
    /// </summary>
    [MaxLength(200)]
    public string? VisualStyle { get; set; }
}
